title: AgriLab UniLaSalle
description: FabLab d'UniLaSalle
permalink: pretty

remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0

plugins:
  - jekyll-remote-theme

navbar:
  - title: Projets
    dropdown:
      - title: AgriTEC 1
        url: /AgriTec/AgriTEC1.md
      - title: AgriTEC 2
        url: /AgriTec/AgriTEC2.md
      - title: AgriTEC 3
        url: /AgriTec/AgriTEC3.md
